In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [4]:
nameVectors = pd.read_csv('professorNameVectors.csv')

nameVectors

0         1         2         3         4         5         6  \
0  -0.335974 -0.144979  2.124863  0.275870  0.597233  0.261455  0.579504   
1  -0.142549 -0.144021  1.868421  0.361041  0.132073  0.637765 -0.195492   
2   0.247835  0.694078  1.956438 -0.103844 -0.120681  0.563798  0.435648   
3  -0.305284  0.482715  1.953541  0.363761  0.621241  0.909956  0.137432   
4  -0.489110  0.155435  0.941998  0.102931  0.334067  0.764465 -0.230521   
5   0.203133 -0.132610  1.870306  0.102021  0.632521  0.522936 -0.799153   
6  -0.197338  0.159835  1.691072 -0.098642  0.791572  0.711045 -0.489952   
7   0.113451  0.431301  0.597997  0.195035  0.664783  0.792210 -0.403156   
8   0.105628  0.506767  1.270523 -0.000906 -0.006827  0.043181  0.190590   
9   0.293792 -0.393463  1.339435 -0.186632  0.250981  0.737813 -0.515525   
10  0.034676  0.047184  1.614140 -0.357088  0.493486  0.115265  0.149113   
11 -0.056695 -0.346210  1.172684  0.041394  0.802520  0.200110 -0.556163   
12 -0.153096 -0.449480  1.137939 -0.031042  0.337624  0.464285 -0.378211   
13 -0.666148  0.074094  1.301195  0.475889  0.047938  0.296206 -0.381304   
14  0.352831  0.102841  1.311578 -0.196575  0.228639  1.423314 -0.355230   
15  0.217337  0.277835  1.425300  0.297992 -0.263348  0.794378  0.242602   
16  0.004860  0.403591  1.610291 -0.301539  0.293840  0.644878  0.130031   
17 -0.230089  0.035782  1.166550 -0.006722  0.669809  1.108810  0.438516   
18 -0.027163 -0.078672  1.957974  0.512800  0.222297 -0.037390 -0.110918   
19 -0.524835  0.044338  1.956584 -0.481913  0.298375  0.844836 -0.082485   
20 -0.152549  0.358555  1.430044  0.178909 -0.058193  0.012524 -0.190112   
21  0.051565  0.468589  2.049007 -0.177817  0.116742  1.130907  0.679650   
22 -0.659700  0.726246  1.620022 -0.268519  0.079789  0.682637  0.064727   
23  0.502378  0.294799  1.911662  0.093439  0.379514  0.525861 -0.415086   
24  0.680447  0.491559  1.488722  0.189060  0.258631  0.886606 -0.084105   
25 -0.136359  0.077045  1.483862  0.042872  0.193605  0.671777 -0.100976   
26  0.255742  0.327140  1.385798 -0.421603  0.449518  0.642815  0.426696   
27  0.079626 -0.870810  1.690578 -0.011527  0.696831  0.720029 -0.947709   
28  0.438807 -0.069465  1.222288  0.200851  1.015559  0.399458  0.100549   
29  0.106298  1.371568  1.773054  0.306382  0.199356  0.467857  0.604103   
30 -0.088646  0.238288  1.561061 -0.101453  0.446597  0.680812  0.424074   
31  0.308230 -0.578582  1.857287  0.263500  0.508502  0.621002  0.065904   
32  0.105662 -0.197819  2.082472  0.406251  0.671027  0.813451 -0.808877   
33  0.259879  0.441915  1.134907 -0.187127  0.402887  0.964300 -0.537588   
34  0.193502  0.290434  1.111784  0.298170  0.378245  0.315894 -0.847980   
35 -0.022653 -0.099182  1.326891  0.270568  0.610622  0.594422 -0.753482   
36 -0.040151  0.737667  1.022400 -0.735182 -0.084947  1.254368  0.669103   
37 -0.182547  0.389265  1.048114 -0.102257 -0.278430  1.040092  0.268686   
38  0.482545  0.360630  1.278618 -0.192497  0.256951  0.587248 -0.469965   
39 -0.112965  0.386689  1.535351  0.027767  0.111455  1.022334  0.029299   

           7         8         9  ...       759       760       761       762  \
0  -0.236608 -0.284806 -0.464326  ... -1.000391  0.219154  0.435004 -0.229378   
1   0.570052 -0.614729  0.061121  ... -0.330566  0.307446  0.678635  0.091712   
2   0.635740 -0.326389 -0.458770  ... -0.174018  0.484976  0.431421 -0.133045   
3   0.426226 -0.563196  0.309772  ...  0.579833  0.255115  0.578893 -0.502683   
4   0.293483 -0.405555 -0.155513  ...  0.131525  0.804771  0.656158 -0.192200   
5   0.890857  0.012833 -0.471756  ...  0.209160 -0.049317  0.519031  0.204123   
6   0.713313 -0.588928  0.027149  ... -0.774000  0.381688  0.381698  0.334207   
7  -0.083098 -1.128624 -0.371238  ...  0.002408  0.772906  0.903700  0.145068   
8   0.207161 -0.101000  0.052505  ... -0.150363  0.371047  0.645610 -0.671911   
9   0.405408 -0.377055 -0.211029  ... -0.772352  0.145157  0.300892  0.216453   
10 

In [5]:
nameVectors = pd.read_csv('professorNameVectors.csv')

names = nameVectors['names']

del nameVectors['names']
nameVectorsNP = nameVectors.values

NN = NearestNeighbors(n_neighbors=5)

NN.fit(nameVectorsNP)

NearestNeighbors()

In [6]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('bert-base-nli-mean-tokens')

/Users/himme/Downloads/code/hw2/2/.venv/lib/python3.12/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/Users/himme/Downloads/code/hw2/2/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [7]:
inputVector = model.encode('Andrew Freedman')

inputVector

array([-3.26005399e-01,  1.84936434e-01,  1.56939030e+00,  4.35722284e-02,
        5.71844280e-01,  6.12395167e-01,  4.22617257e-01, -1.23044506e-01,
       -3.77907574e-01, -2.72839606e-01, -1.10639477e+00,  1.84840113e-01,
       -8.45499188e-02,  8.60799551e-02,  1.30004793e-01,  6.79061770e-01,
       -6.15678132e-01, -3.17884743e-01,  3.17248344e-01, -1.09885967e+00,
       -3.95728678e-01,  2.60815650e-01, -7.02549279e-01, -7.21438974e-02,
        2.98908055e-01, -3.53080601e-01,  3.30449373e-01, -2.58368731e+00,
       -3.76366556e-01,  1.49212748e-01,  1.94923013e-01, -1.68486536e-01,
        7.98684716e-01,  2.17432931e-01, -9.20202851e-01,  5.40264726e-01,
       -5.01202047e-01,  1.77497610e-01, -3.70364517e-01, -1.48303481e-02,
        1.38915575e+00, -3.01908940e-01,  6.27584159e-01,  4.15036589e-01,
       -8.29802155e-01, -8.10883269e-02,  6.53587997e-01, -7.81024337e-01,
       -4.58143428e-02, -1.38244998e+00, -1.87662497e-01, -3.73896748e-01,
       -2.61955142e-01,  

In [8]:
distances, indices = NN.kneighbors([inputVector])

indices[0]

array([ 0,  6, 33, 15, 25])

In [9]:
type(indices)

numpy.ndarray

In [10]:
names

0           Andrew Freed\n
1           Tim Delworth\n
2           Craig Miller\n
3        Buster Dunsmore\n
4              John Nash\n
5            Ray Decarlo\n
6         Philip Mummert\n
7           Johnny Brown\n
8         Ralph Kaufmann\n
9       Denise Zielinski\n
10        Saurabh Bagchi\n
11            Alex Quinn\n
12           Jill Gulker\n
13            Gary Evans\n
14        Stephen Setman\n
15         Paul Wenthold\n
16           Jon Teaford\n
17         Morgan Murphy\n
18     Brent Branstetter\n
19          Nicole Hands\n
20          Rick Kennell\n
21          Greg Francis\n
22     Jonathon Peterson\n
23         Sai-Kee Yeung\n
24          Robert Ogles\n
25         Chris Clifton\n
26        James Garrison\n
27        Carina Rebello\n
28     Priya Rajagopalan\n
29         Abram Axelrod\n
30         James Gothard\n
31    Geraldine Friedman\n
32         Raymond Cipra\n
33          John Dunning\n
34         Cheng-Kok Koh\n
35     Laura Pyrak-Nolte\n
36         Michael Jacob\n
3

In [11]:


indices

array([[ 0,  6, 33, 15, 25]])

In [12]:
names.iloc[indices[0]]

0       Andrew Freed\n
6     Philip Mummert\n
33      John Dunning\n
15     Paul Wenthold\n
25     Chris Clifton\n
Name: names, dtype: object

In [13]:
import pickle
with open('knn.pkl', 'wb') as f:
    pickle.dump(NN, f)